// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxtcwkykmpatavpgfzej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4dGN3a3lrbXBhdGF2cGdmemVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMTcxMzksImV4cCI6MjA2MzU5MzEzOX0.2Qnu-bUjuWhP8tNH_kQfcX1LrsjpiCFcvumGwikCcgk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);